
name: CI

on:
  push:

  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: YAML Lint and Shellcheck
        uses: jason-idk/gh-actions/.github/actions/gha-linter@feature/baseline-actions

      - name: Semantic versioning
        uses: jason-idk/gh-actions/.github/actions/semantic-versioning@feature/baseline-actions
        with:
          main_branch: main